//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class juegos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public juegos()
        {
            this.Usuarios2 = new HashSet<Usuarios2>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public string categoria { get; set; }
        public string comentario { get; set; }
        public string tags { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios2> Usuarios2 { get; set; }
    }
}
