//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios2
    {
        public int Id { get; set; }
        public Nullable<int> juegoid { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string comentario { get; set; }
    
        public virtual juegos juegos { get; set; }
    }
}
